env_name: cartpole-v1
env_entry_point: env.cartpole:CartPoleEnv
max_episode_steps: 200
depth: 15
transition_fn: env.transition_fns:cartpole
reward_fn: env.reward_fns:cartpole
discrete: True
render: True

disprod:
  n_restarts: 200
  step_size: 10
  step_size_var: 1
