env_name: continuous-dubins-car-ablation-v0
env_entry_point: env.continuous_dubins_car_ablation:ContinuousDubinsCarAblation
max_episode_steps: 750
depth: 100
reward_fn: env.reward_fns:continuous_dubins_car_leaky
discrete: False
render: True
run_mode: production
plot_imagined_trajectory: True

cem:
  n_samples: 100
  mpc_steps: 100

mppi:
  n_samples: 2000
  gamma: 1.0
  mpc_steps: 100

disprod:
  step_size: 0.1
  step_size_var: 0.01
  n_restarts: 100