env_name: continuous-dubins-car-v0
env_entry_point: env.continuous_dubins_car:ContinuousDubinsCar
max_episode_steps: 200
depth: 100 # can use 50 for Gym
transition_fn: env.transition_fns:continuous_dubins_car
reward_fn: env.reward_fns:continuous_dubins_car
discrete: False
noise: False
log_file: None
render: True
debug: True
add_obstacles: True
# This file is used for experiments with ROS/Jackal/Heron as we don't need the Gym environment.
env_file: env.continuous_dubins_env_properties:EnvironmentProperties
vehicle_model: turtlebot ## or jackal
ros_interface: planners.ros_interface:plan_one_step_dubins_car
fixed_time_pub_mode: False
# Set this to true to plot the hallucinated states that the planner thinks it will visit.
plot_imagined_trajectory: False

mppi:
  n_samples: 400
  gamma: 10000

# For some maps, a step_size of 1, and step_size_var of 0.1 might work better.
disprod:
  step_size: 10
  step_size_var: 1
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  # Modes: complete, no_var
  taylor_expansion_mode: no_var