env_name: continuous-dubins-car-w-velocity-state-v0
env_entry_point: env.continuous_dubins_car_w_velocity_state:ContinuousDubinsCar
max_episode_steps: 200
n_restarts: 400
depth: 100
transition_fn: env.transition_fns:continuous_dubins_car_w_velocity_state
reward_fn: env.reward_fns:continuous_dubins_car_w_velocity
discrete: False
noise: False
log_file: None
render: True
debug: True
add_obstacles: True
# This file is used for experiments with ROS/Jackal/Heron as we don't need the Gym environment.
env_file: env.continuous_dubins_env_properties_w_velocity:EnvironmentProperties
vehicle_model: turtlebot ## or jackal
ros_interface: planners.ros_interface:plan_one_step_dubins_car_w_velocity
fixed_time_pub_mode: False



mppi:
  n_samples: 400
  gamma: 10000

disprod:
  step_size: 10
  step_size_var: 1
  n_restarts: 200
  choose_action_mean: False
  reward_fn_using_taylor: True
  max_grad_steps: 10
  # Modes: complete, no_var
  taylor_expansion_mode: no_var