env_name: mountain-car-v2
env_entry_point: env.mountain_car:MountainCarEnv
max_episode_steps: 200
depth: 100
transition_fn: env.transition_fns:mountain_car
reward_fn: env.reward_fns:mountain_car
discrete: True
reward_sparsity: 1

disprod:
  step_size: 0.1
  step_size_var: 0.01
  n_restarts: 200