env_name: mountain-car-v2
env_entry_point: env.mountain_car:MountainCarEnv
max_episode_steps: 200
depth: 100
reward_fn: env.reward_fns:mountain_car
discrete: True
reward_sparsity: 1

disprod:
  step_size: 0.001
  step_size_var: 0.0001
  n_restarts: 10